Port relevant changes to do-major-upgrade.sh.j2 from task/1.y/major-upgrade-hubkey-switch

diff --git a/config/ansible/major_upgrade/templates/do-major-upgrade.sh.j2 b/config/ansible/major_upgrade/templates/do-major-upgrade.sh.j2
--- a/config/ansible/major_upgrade/templates/do-major-upgrade.sh.j2
+++ b/config/ansible/major_upgrade/templates/do-major-upgrade.sh.j2
@@ -32,10 +32,9 @@ else
 fi
 
 ###############################
-# Remove rootfs overlayconf file (so if extraction step fails or is interrupted, will still boot into old underlay).
+# Backup/remove rootfs overlayconf file (so if extraction step fails or is interrupted, will still boot into old underlay).
 ###############################
-
-rm -f /etc/overlayroot.conf
+mv /etc/overlayroot.conf /etc/overlayroot.conf.bak
 
 ###############################
 # Extract new rootfs
@@ -119,7 +118,22 @@ if [ -e /boot/grub/grub.cfg ]; then
         mount --move "$mountpoint" "$new_mount"
     done
 
-    if [ "$(cloud-init query cloud_id)" = "nocloud" ]; then
+    # install grub
+    root_partition=$(findmnt -n -o SOURCE /)
+    root_device=$(lsblk -no PKNAME "$root_partition")
+
+    mount -o remount,rw $boot_mountpoint
+    mount -o bind $boot_mountpoint /boot/efi
+
+    if ! grub-install "/dev/$root_device" --no-uefi-secure-boot --removable; then
+        # older VMs use BIOS
+        apt-get -y remove grub-efi-amd64
+        apt-get -y install grub-pc
+        grub-install "/dev/$root_device" --target=i386-pc
+    fi
+
+    # update grub
+    if ! which cloud-init || [ "$(cloud-init query cloud_id)" = "nocloud" ] || [ "$(cloud-init query cloud_id)" = "" ]; then
         # VirtualBox cloud init source
         sed -i 's|\(GRUB_CMDLINE_LINUX_DEFAULT=".*\)"|\1 ds=nocloud\\;s=file:///etc/jaiabot/init/ network-config=disabled"|' /etc/default/grub
     elif [ "$(cloud-init query cloud_id)" = "aws" ]; then       
@@ -128,14 +142,6 @@ if [ -e /boot/grub/grub.cfg ]; then
     fi
        
     update-grub
-    
-    root_partition=$(findmnt -n -o SOURCE /)
-    root_device=$(lsblk -no PKNAME "$root_partition")
-
-    mount -o remount,rw $boot_mountpoint
-    mount -o bind $boot_mountpoint /boot/efi
-
-    grub-install "/dev/$root_device" --no-uefi-secure-boot --removable
 fi
 
 if [ "{{ upgrade_type }}" = "embedded" ]; then
